import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import devMike from "../public/avatar1.jpg";
import code from "../public/code.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  console.log(darkMode);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mike Miller Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 m:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">Mike Miller</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                {/*  <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">
                  Resume
                </a> */}
              </li>
              <li></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-500 font-medium md:text-6xl">Mike Miller</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Web-Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              I’m looking for an interesting new job as a Frontend Developer in/near Freiburg im Breisgau or fully
              remote.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py- text-gray-600 dark:text-white">
            <Link href={"https://github.com/Mikex95"}>
              <AiFillGithub className="hover:translate-y-[-1px]" />
            </Link>
            <Link href={"https://www.linkedin.com/in/mike-miller-95x/"}>
              <AiFillLinkedin className="hover:translate-y-[-1px]" />
            </Link>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden border-4 shadow-2xl border-teal-500 hover:translate-y-[-1px] md:h-96 md:w-96">
            <Image alt="Mike" src={devMike} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div className="text-center mt-10">
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-80 max-w-3xl mx-auto dark:text-white">
              As a junior front-end developer, I <span className="text-teal-500">enjoy</span> creating visually
              appealing and user-friendly websites. I also have experience with backend development using the MERN
              stack. I am <span className="text-teal-500"> highly motivated </span> to continue learning and growing in
              my skills and knowledge.
            </p>
          </div>
          <div>
            <div className="text-center shadow-lg flex justify-center items-center flex-col p-5 rounded-xl my-5 dark:text-white">
              <Image alt="icon" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 md:text-2xl">I love programming</h3>
              <p>Creating elegant Websites suited for your needs</p>
              <h4 className="py-4 text-teal-600">Coding tools I use</h4>
              <section className="flex gap-5 mt-10 ">
                <div className="shadow-lg p-5 mb-10 rounded-xl dark:text-white">
                  <h4 className="mb-3 text-2xl text-teal-300">Frontend</h4>
                  <p className="text-gray-800 py-1 dark:text-white">HTML</p>
                  <p className="text-gray-800 py-1 dark:text-white">CSS</p>
                  <p className="text-gray-800 py-1 dark:text-white">Javascript</p>
                  <p className="text-gray-800 py-1 dark:text-white">React.js</p>
                </div>

                <div className="shadow-lg p-5 mb-10 rounded-xl">
                  <h4 className="mb-3 text-2xl text-teal-300">Backend</h4>
                  <p className="text-gray-800 py-1 dark:text-white">Node.js</p>
                  <p className="text-gray-800 py-1 dark:text-white">Express.js</p>
                  <p className="text-gray-800 py-1 dark:text-white">MongoDB</p>
                </div>
              </section>
            </div>
          </div>
        </section>
        <section>
          <div className="pb-5">
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md max-w-6xl py-2 leading-8 text-gray-800 dark:text-white">
              My passion for software and hardware led me to attend an intensive coding bootcamp where I gained
              expertise in HTML, CSS, JS, React, Node.js, and more. Throughout the program, I worked on personal
              projects, such as creating responsive websites and building interactive applications. Here are a few
              examples:
            </p>
          </div>
          <div className=" pb-10 grid  gap-5 md:grid-cols-2">
            <div>
              <Link href={"https://mikex95.github.io/Flying-dude/"}>
                <Image
                  className="rounded-lg object-cover shadow-sm hover:translate-y-[-1px]"
                  width="100%"
                  src={web1}
                  alt="projects"
                />
              </Link>
            </div>
            <div>
              <Link href={"https://mikex95.github.io/super-code-shop/"}>
                <Image
                  className="rounded-lg object-cover shadow-sm hover:translate-y-[-1px]"
                  width={"100%"}
                  src={web2}
                  alt="projects"
                />
              </Link>
            </div>
            <div>
              <Image
                className="rounded-lg object-cover hover:translate-y-[-1px]"
                width="100%"
                src={web3}
                alt="projects"
              />
            </div>
            <div>
              <Link href={"https://iridescent-maamoul-d8c323.netlify.app/"}>
                <Image
                  className="rounded-lg object-cover hover:translate-y-[-1px]"
                  width={"100%"}
                  src={web4}
                  alt="projects"
                />
              </Link>
            </div>
            <div>
              <Link href={"https://e-commerce-shop-supercode.netlify.app/"}>
                <Image
                  className="rounded-lg object-cover hover:translate-y-[-1px]"
                  width={"100%"}
                  src={web5}
                  alt="projects"
                />
              </Link>
            </div>
            <div>
              <Link href={"https://gros-shop-app.onrender.com/onboarding"}>
                <Image
                  className="rounded-lg object-cover hover:translate-y-[-1px]"
                  width={"100%"}
                  height={"100%"}
                  src={web6}
                  alt="projects"
                />
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
